{
 "title": "openc3-cadvisor & docker monitor",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(openc3_cadvisor_net_if_out_packets, cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(openc3_cadvisor_net_if_out_packets{cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "task",
    "label": "task",
    "query": {
     "query": "label_values(openc3_cadvisor_net_if_out_packets{cluster=~\"$cluster\",namespace=~\"$namespace\"}, task)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "cores used",
   "type": "graph",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "openc3_cadvisor_cpu_busy{cluster=~\"$cluster\",namespace=~\"$namespace\",task=~\"$task\"}/100",
     "legendFormat": "{{instance}}:{{name}}:{{id}}"
    }
   ]
  },
  {
   "title": "cores kernel",
   "type": "graph",
   "gridPos": { "h": 14, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "openc3_cadvisor_cpu_system{cluster=~\"$cluster\",namespace=~\"$namespace\",task=~\"$task\"} / 100",
     "legendFormat": "{{instance}}:{{name}}:{{id}}"
    }
   ]
  },
  {
   "title": "cores user",
   "type": "graph",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "openc3_cadvisor_cpu_user{cluster=~\"$cluster\",namespace=~\"$namespace\",task=~\"$task\"} / 100",
     "legendFormat": "{{instance}}:{{name}}:{{id}}"
    }
   ]
  },
  {
   "title": "mem used",
   "type": "graph",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "openc3_cadvisor_mem_memused{cluster=~\"$cluster\",namespace=~\"$namespace\",task=~\"$task\"}",
     "legendFormat": "{{instance}}:{{name}}:{{id}}"
    }
   ]
  },
  {
   "title": "mem used %",
   "type": "graph",
   "gridPos": { "h": 14, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "openc3_cadvisor_mem_memused_percent{cluster=~\"$cluster\",namespace=~\"$namespace\",task=~\"$task\"}",
     "legendFormat": "{{instance}}:{{name}}:{{id}}"
    }
   ]
  },
  {
   "title": "rrs used %",
   "type": "graph",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "openc3_cadvisor_mem_rrsused_percent{cluster=~\"$cluster\",namespace=~\"$namespace\",task=~\"$task\"}",
     "legendFormat": "{{instance}}:{{name}}:{{id}}"
    }
   ]
  }
 ]
}